# Generated by Django 4.2.25 on 2025-11-03 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
            ],
            options={
                'verbose_name': 'Ator',
                'verbose_name_plural': 'Atores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2026)], verbose_name='Ano de lançamento')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='movies/photos/%Y/%m/', verbose_name='Foto do filme')),
                ('trailer_url', models.URLField(blank=True, null=True, verbose_name='URL do trailer')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Nota')),
                ('actors', models.ManyToManyField(related_name='movies', to='movies.actor', verbose_name='Atores')),
                ('categories', models.ManyToManyField(related_name='movies', to='movies.category', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ['-release_year', 'title'],
            },
        ),
    ]
